version: "3.7"
services:

  consignment-cli:
    build: ./consignment-cli
    environment:
      - MICRO_REGISTRY=mdns
  
  user-cli:
    build: ./user-cli
    environment:
      - MICRO_REGISTRY=mdns

  consignment-service:
    container_name: shippy_consignment_service
    build: ./consignment-service
    ports:
      - 50051:50051
    environment:
      - MICRO_ADDRESS=:50051
      - MICRO_REGISTRY=mdns
      - DB_HOST=shippy_datastore:27017

  vessel-service:
    container_name: shippy_vessel_service
    build: ./vessel-service
    ports:
      - 50052:50051
    environment:
      - MICRO_ADDRESS=:50051
      - MICRO_REGISTRY=mdns
      - DB_HOST=shippy_datastore:27017

  user-service:
    container_name: shippy_user_service
    build: ./user-service
    ports:
      - 50053:50051
    environment:
      - MICRO_ADDRESS=:50051
      - MICRO_REGISTRY=mdns
      - DB_NAME=postgres
      - DB_HOST=shippy_database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - database
  
  datastore:
    image: mongo
    container_name: shippy_datastore
    ports:
      - 27017:27017
  
  database:
    image: postgres
    container_name: shippy_database
    ports:
      - 5432:5432